import type { AnalyticsConfig, EventParameterDef } from '../config/schema.js';

const TS_TYPE: Record<EventParameterDef['type'], string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  items: 'Item[]',
};

// GA4 ecommerce item fields (developers.google.com/analytics/devguides/collection/ga4/reference/events),
// verified 2026-08-29. item_id or item_name is required; both are optional here to keep the generated
// type simple, GA4 itself is the source of truth for that constraint.
const ITEM_INTERFACE = [
  'export interface Item {',
  '  item_id?: string;',
  '  item_name?: string;',
  '  affiliation?: string;',
  '  coupon?: string;',
  '  discount?: number;',
  '  index?: number;',
  '  item_brand?: string;',
  '  item_category?: string;',
  '  item_category2?: string;',
  '  item_category3?: string;',
  '  item_category4?: string;',
  '  item_category5?: string;',
  '  item_list_id?: string;',
  '  item_list_name?: string;',
  '  item_variant?: string;',
  '  location_id?: string;',
  '  price?: number;',
  '  quantity?: number;',
  '}',
  '',
];

function toTypeName(eventName: string): string {
  return eventName
    .split('_')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

export function generateEventTypes(config: AnalyticsConfig): string {
  const eventNames = Object.keys(config.events).sort();
  const lines: string[] = [
    '// Generated by `gtm-code generate`. Do not edit by hand, regenerate from the config instead.',
    '',
  ];

  const usesItems = eventNames.some((name) =>
    Object.values(config.events[name].parameters).some((param) => param.type === 'items'),
  );
  if (usesItems) lines.push(...ITEM_INTERFACE);

  if (eventNames.length === 0) {
    lines.push('export type EventName = never;', '', 'export interface EventParams {}', '');
  } else {
    lines.push(`export type EventName = ${eventNames.map((name) => `'${name}'`).join(' | ')};`, '');

    for (const name of eventNames) {
      const event = config.events[name];
      const paramNames = Object.keys(event.parameters);
      lines.push(`export interface ${toTypeName(name)}Params {`);
      if (paramNames.length === 0) lines.push('  // no parameters');
      for (const paramName of paramNames) {
        const param = event.parameters[paramName];
        lines.push(`  ${paramName}${param.optional ? '?' : ''}: ${TS_TYPE[param.type]};`);
      }
      lines.push('}', '');
    }

    lines.push('export interface EventParams {');
    for (const name of eventNames) lines.push(`  ${name}: ${toTypeName(name)}Params;`);
    lines.push('}', '');
  }

  lines.push(
    'declare global {',
    '  interface Window {',
    '    dataLayer: unknown[];',
    '  }',
    '}',
    '',
    'export function track<E extends EventName>(event: E, params: EventParams[E]): void {',
    '  window.dataLayer = window.dataLayer || [];',
    '  window.dataLayer.push({ event, ...params });',
    '}',
    '',
  );

  return lines.join('\n');
}
