import type { AnalyticsConfig, EventParameterDef } from '../config/schema.js';

const TS_TYPE: Record<EventParameterDef['type'], string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
};

function toTypeName(eventName: string): string {
  return eventName
    .split('_')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

export function generateEventTypes(config: AnalyticsConfig): string {
  const eventNames = Object.keys(config.events).sort();
  const lines: string[] = [
    '// Generated by `gtm-code generate`. Do not edit by hand, regenerate from the config instead.',
    '',
  ];

  if (eventNames.length === 0) {
    lines.push('export type EventName = never;', '', 'export interface EventParams {}', '');
  } else {
    lines.push(`export type EventName = ${eventNames.map((name) => `'${name}'`).join(' | ')};`, '');

    for (const name of eventNames) {
      const event = config.events[name];
      const paramNames = Object.keys(event.parameters);
      lines.push(`export interface ${toTypeName(name)}Params {`);
      if (paramNames.length === 0) lines.push('  // no parameters');
      for (const paramName of paramNames) {
        const param = event.parameters[paramName];
        lines.push(`  ${paramName}${param.optional ? '?' : ''}: ${TS_TYPE[param.type]};`);
      }
      lines.push('}', '');
    }

    lines.push('export interface EventParams {');
    for (const name of eventNames) lines.push(`  ${name}: ${toTypeName(name)}Params;`);
    lines.push('}', '');
  }

  lines.push(
    'declare global {',
    '  interface Window {',
    '    dataLayer: unknown[];',
    '  }',
    '}',
    '',
    'export function track<E extends EventName>(event: E, params: EventParams[E]): void {',
    '  window.dataLayer = window.dataLayer || [];',
    '  window.dataLayer.push({ event, ...params });',
    '}',
    '',
  );

  return lines.join('\n');
}
